### ISSUE TITLE
Unable to withdraw using CLI

### ISSUE THREAD

**Issue by orkunkilic** [InternetMaximalism/intmax2-mining-cli#24]
Hi, I was testing the product with some local deployments, and at the same time I tried the mining. It was going well for the first 3 deposits, however now I am unable to withdraw my funds. I guess this is because some version mismatch between the server you are running and the CLI. Simply my logs are as follows:

`22:54:56 [INFO] Submitting withdrawal to https://v1.mining-gateway.intmax.xyz/v1/withdrawal, body: SubmitWithdrawalInput { public_inputs: SimpleWithdrawalPublicInputs { ...HIDDEN... }
22:54:58 [ERROR] Internal error: Failed to withdrawal: Serialization error: failed to parse response: error decoding response body: data did not match any variant of untagged enum SumbitWithdrawalResponse`

**Comment by kbizikav** [comment]
I apologize for the inconvenience.

Due to an inconsistency in the config file, withdrawals failed for users who launched the CLI after approximately 10:00 UTC on the 18th. This problem has been resolved in the current latest version (v1.1.0).

**Comment by kbizikav** [comment]
I'll close this issue, but if the problem persists, please feel free to reopen it.

**Comment by Hogen32** [comment]
Hi I can't find my coin in tonkeeper wallet I can see I can see they have been sent but they are in wallet I have never been able to receive coin in my wallet only pay
