### ISSUE TITLE
https://hackmd.io/zNLtkMXXSCernbkTf1BTrQ

### ISSUE THREAD

**Issue by Samhuri** [InternetMaximalism/intmax2-mining-cli#42]

**Comment by Samhuri** [comment]
Aku belum mengerti cara penggunaannya. Namun akan tetap aku garap

**Comment by Wahyuaak1** [comment]
Tutor cara garap ny bagaimna bang?

**Comment by Wahyuaak1** [comment]
Bismillah smoga jp ya Allah mau nyenengin ortu

**Comment by Samhuri** [comment]
> Tutor cara garap ny bagaimna bang?

Akupun lupa garapannya. Saking banyak garapan tapi belum cuan 😁
